cloudoperators/greenhouse

Dockerfile

This removes the tests from the docker build.
Out of scope: Incorporation of tests into gh actions before image builds. 
fyi @kengou

fix(manager): Remove tests from docker build

---

cmd/dev-env/main.go
pkg/controllers/organization/rbac_controller.go
pkg/controllers/organization/rbac_controller_test.go
pkg/idproxy/connector.go
pkg/rbac/clusterrole.go
pkg/rbac/role.go
pkg/rbac/util.go

Org Admins are granted the ability to create RoleBindings. With [restrictions-on-role-binding-creation-or-update](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-binding-creation-or-update) they can only grant access contained by the OrgAdmin role.
The roles ClusterAdmin and PluginAdmin respectively grant the abilities for editing Clusters & Plugins respectively
Changes:
- each org receives a dedicated rbacv1.Role for Cluster and Plugin Admins
- refactor funcs for role names and policy rules

feat(greenhouse-rbac): add ClusterAdmin and PluginAdmin roles

---

Dockerfile.dev-env

The lib was upgraded to go1.22, this pins it to the last commit before to avoid the forced upgrade.

fix(dev-env): pin setup-envtest version in dockerfile

---

.github/workflows/docker-build.yaml

`--template sarif.tpl` is deprecated, migrate to `--format sarif`

fix(gh-action) trivy scan format: template is deprecated

---

.github/workflows/docker-build.yaml

upload `SARIF` results to `GitHub Code` scanning even upon a non zero exit code from `Trivy Scan`

fix(gh-actions) run in paralell/ always upload trivy

---

ui/cluster-admin/package-lock.json
ui/cluster-admin/package.json

"Latest" doesn't work for dependencies. If they change then the sha hash of the version originally used and stored in `package-lock.json` doesn't match the sha hash of the current version anymore which leads to inconsistencies.

Fix dependencies. Don't use latest

---

pkg/rbac/role.go

This feature allows admins within a Organization to maintain Team RBAC.
OrgAdmins gain permissions to CRUD TeamRoles & TeamRoleBindings.
ClusteAdmins gain permissiosn to CRUD TeamRoleBindings.

feat(teamrbac): grant permissions to OrgAdmins and ClusterAdmins

---

.github/CODEOWNERS

More fine granular handling of CODEOWNERS to reduce Github Notifications for the team.
`/docs/reference/api` contains the API documentation generated from the Go Structs for the Greenhouse CRDs
- [] 🍕 Feature

fix(codeowners): dedicated entry for openapi docs

---

pkg/rbac/role.go

OrgAdmins, ClusterAdmins, PluginAdmins should be allowed to edit PluginConfigs but not Plugins.
This PR fixes this regression.

fix(rbac): allow PluginAdmins to edit PluginConfigs

---

ui/plugin-admin/package-lock.json
ui/plugin-admin/package.json
ui/plugin-admin/src/components/PluginDetail.js

There was a runtime error for unexpectedly deeply nested options. Fixed it by removing the logic that tried to differentiate between arrays and objects and instead used `JsonViewer` also for arrays. Also updated the `JsonViewer` component in `juno-ui-components` to also allow arrays.

[plugin-admin] Fix deep nested options

---

ui/team-admin/package-lock.json
ui/team-admin/package.json

This is done to remove the following vulnarabilities'alert
https://github.com/cloudoperators/greenhouse/security/dependabot/9
Note: The Zustand Version 4.5.2 is necessary for the latest version of messages-provider lib.

[team-admin] Update the zustand and messages-provider versions

---

pkg/controllers/pluginconfig/helm_controller.go
pkg/controllers/pluginconfig/remote_cluster_test.go

With the introduction of the DriftDetection only a Drift triggered a helm deployment.
But a Diff between the deployed and the current release of the Plugin should trigger a helm deploy as well.
This change ensures that only if no drift and no diff there is a NOOP.

fix(helmcontroller): fix regression that diff was not reconciled

---

pkg/apis/greenhouse/v1alpha1/teamrole_types.go
pkg/apis/greenhouse/v1alpha1/teamrolebinding_types.go
pkg/apis/well_known.go
pkg/controllers/teamrbac/suite_test.go
pkg/controllers/teamrbac/teamrolebinding_controller.go
pkg/controllers/teamrbac/teamrolebinding_controller_test.go

- regression: the rbac prefixes were not considered during deletion logic
- labels are now added correctly with clientutil.CreateOrPatch
- ClusterRole is removed, once all referencing Role, ClusterRole are deleted

fix(teamrbac): fix deletion logic, fix labeling

---

charts/manager/crds/greenhouse.sap_plugins.yaml
charts/manager/templates/manager-role.yaml
docs/reference/api/index.html
docs/reference/api/openapi.yaml
pkg/admission/plugin_webhook.go
pkg/apis/greenhouse/v1alpha1/plugin_types.go
pkg/controllers/plugin/helm_controller.go
pkg/controllers/plugin/remote_cluster_test.go
pkg/controllers/plugin/suite_test.go
pkg/helm/helm.go
pkg/helm/helm_test.go

configurable namespace for a pluginconfig release

---

cmd/service-proxy/proxy_test.go
pkg/admission/plugin_webhook.go
pkg/admission/plugindefinition_webhook.go
pkg/admission/plugindefinition_webhook_test.go
pkg/apis/well_known.go
pkg/controllers/plugin/helm_controller.go
pkg/test/util.go

PluginDefinitions which are used by one or more Plugins must not be deleted
Migrate to use 'greenhouse.sap/plugindefinition' label for Plugins. Delete 'greenhouse.sap/plugin' label from Plugins

fix: deny deletion of used plugindefinitions, migrate label

---

.github/renovate.json

Dex versions are not compatible with Go nor dependabot. See: https://github.com/dexidp/dex/issues/2880

fix(renovate): ignore dexidp since go mod version not supported

---

charts/manager/crds/kustomization.yaml

The CRD for PluginPresets is missing due to the missing registration in kustomzation.yaml

fix(pluginpreset): add crd to kustomization

---

pkg/helm/helm.go

the Plugin Namespace must not be the same as the release namespace This can cause unwanted behaviour when diffing deployed and rendered manifest resources

fix(helm): diff with the plugins release namespace

---

pkg/controllers/plugin/helm_controller.go
pkg/controllers/plugin/remote_cluster_test.go

Fix for a regression introduced with the releaseNamespaces. 
The namespace of the kube client is used to determine the namespace for a Helm resource without explicit namespace in the template. This resulted in some resource being deployed to the default greenhouse managed namespace, while others where deployed to the releaseNamespace.

fix(helm): ensure releaseNamespace is set on clientGetter

---

pkg/rbac/role.go

The alerts plugin can be deployed into the org namespace of the central cluster. In order to enable the org admins to debug configuration issues, it is necessary to permit them to view `alertmanger` and `alertmanagerconfig` resources within their org namespace.
The RBAC has not been added to the PluginDefinition to have one Place to see the permissions for an Organisation Administrator.

feat(rbac): permit org admins to debug alertmangers

---

pkg/admission/plugin_webhook.go
pkg/admission/plugin_webhook_test.go

The `releaseNamespace` of a Plugin must be immutable. Also fixes regression where `ValidateUpdate` did not compare the old with the current object.

fix(plugin): admission validate immutable releaseNamespace

---

Makefile

The kubernetes version used for running envtests is outdated. This starts to show in security warnings for binaries build with older versions of golang.

chore(envtest): bump used k8s version

---

pkg/helm/helm_test.go
pkg/helm/values.go

This enables plugin developers to use these values also in sub-charts of their plugin.
Also ensures that the `clusterNames` only contain the clusters from the org namespace the plugin resides in
resolves #101

feat(plugin): move greenhouse values to helm global scope

---

pkg/admission/plugin_webhook.go

Plugins do not have the releaseNamespace set if they were created before it was introduced.
This ensures the AdmissionWebhook does not block the defaulting of the releaseNamespace for existing Plugins.
Once the releaseNamespace is set for all Plugins this can be removed again.

fix(plugin): allow defaulting releaseNamespace during admission

---

ui/cluster-admin/package-lock.json
ui/cluster-admin/package.json
ui/cluster-admin/src/AppContent.tsx
ui/cluster-admin/src/components/ClusterDetail.tsx
ui/cluster-admin/src/components/ClusterEdit.tsx
ui/cluster-admin/src/components/KeyValueInput.tsx
ui/cluster-admin/src/components/ResultMessage.tsx
ui/cluster-admin/src/hooks/useApi.ts
ui/cluster-admin/src/hooks/useClusterApi.ts
ui/cluster-admin/src/store.ts

This adds an edit screen to the `Cluster` admin view.
As for now only with the possibility of changing labels.
Out of scope, as this involves interaction with `Secrets`
- Creating Clusters
- Deleting Clusters
- Changing `accessmode`

feat(ui): cluster-admin add edit screen

---

ui/plugin-admin/src/plugin-edit/OptionInput.tsx
ui/plugin-admin/src/plugin-edit/handleFormChange.ts

- allows `OptionValue` identifiers with `.` separators as e.g. `alerts.alertmanager.enabled`
- Don't show valid JSON for consistent UX, only invalid 
- Do not delete empty `optionValues` as `false==""` in javascript

Fix(ui): minor plugin admin fixes

---

Makefile

By default the Makefile will build the `dev-env` and `greenhouse` development images for `linux/amd64`
This PR adds an option to configure the docker platform such as : `make PLATFORM=linux/arm64 docker-build`

feat(makefile): make architecture used to build dev-images configurable

---

.github/renovate.json
.github/workflows/codeql.yaml
Dockerfile
Dockerfile.dev-env
Dockerfile.headscalectl
Dockerfile.tailscale
Dockerfile.tcp-proxy
Makefile
charts/manager/crds/greenhouse.sap_clusters.yaml
charts/manager/crds/greenhouse.sap_organizations.yaml
charts/manager/crds/greenhouse.sap_plugindefinitions.yaml
charts/manager/crds/greenhouse.sap_pluginpresets.yaml
charts/manager/crds/greenhouse.sap_plugins.yaml
charts/manager/crds/greenhouse.sap_teammemberships.yaml
charts/manager/crds/greenhouse.sap_teamrolebindings.yaml
charts/manager/crds/greenhouse.sap_teamroles.yaml
charts/manager/crds/greenhouse.sap_teams.yaml
docs/reference/api/index.html
docs/reference/api/openapi.yaml
go.mod

This PR bumps GO to v1.22. 
Now we can use sigs-k/controller-tools v0.15 in the Makefile.
_Dockerfile.dev-env_ can be unpinned to use sigs-k/controller-runtime@latest

chore: bump to go1.22, controller-tools v0.15

---

pkg/controllers/teamrbac/suite_test.go
pkg/controllers/teamrbac/teamrolebinding_controller.go
pkg/controllers/teamrbac/teamrolebinding_controller_test.go
pkg/test/assert.go
pkg/test/resources.go

This PR brings in `test.TestSetup(..)` which provides some convenience around creating resources in dedicated namespace. Together with helper methods to create resources (e.g. `CreateTeamRoleBinding(..)` or `OnboardCluster(..)` this should help to reduce the manifest boilerplate required to create resources during test setups.
The test restructuring also unveiled missing propagation of errors when the reconciliation failed. They are now returned.

refac(teamrbac): introduce helpers for testing

---

pkg/apis/greenhouse/v1alpha1/teamrole_types.go
pkg/apis/greenhouse/v1alpha1/teamrolebinding_types.go
pkg/controllers/teamrbac/teamrolebinding_controller.go

Adding PrinterColumns to TeamRole [Age], TeamRoleBinding [TeamRole, Team, Ready, Age]
Ensure condition `EmptyClusterList` is updated correctly.

feat(teamrbac): add printercolumns for TeamRole TeamRoleBinding

---

charts/manager/crds/greenhouse.sap_teamrolebindings.yaml
charts/manager/crds/greenhouse.sap_teamroles.yaml

manifests were not regenerated after changing kubebuilder annotations

fix(teamrbac): run generate manifests

---

pkg/apis/well_known.go
pkg/controllers/plugin/util.go
pkg/controllers/plugin/util_test.go

This PR adds the feature to specify a port by name for being exposed. Beforehand it would always default to the first port.
https://github.com/cloudoperators/greenhouse-extensions/pull/173

feat(plugin): make exposed port configurable by name

---

charts/team-membership/templates/cronjob.yaml

This PR stops the team-membership cronjob to spin up new pods when they fail.

fix(team-membership): Do not spin up pods on failure

---

charts/greenhouse/Chart.yaml
charts/greenhouse/etc/retain.sh
charts/greenhouse/templates/container-image-retainer.yaml
charts/greenhouse/values.yaml

Currently we are using a private registry to pull our container images. This registry GC'ed all images not pulled in the last 30d. 
This feature adds a CronJob to make head requests against all images from this registry to keep them from being removed.

feat: adds image-retainer cronjob

---

pkg/admission/plugin_webhook.go
pkg/admission/plugin_webhook_test.go

If the cluster was deleted before uninstalling the plugin then it is no longer possible to edit/delete the plugins. This fix ensures the cluster is only validated during creation. During updates it must only be ensured the cluster ref was not altered.

fix(plugin): remove cluster validation during update

---

charts/greenhouse/Chart.lock
charts/greenhouse/Chart.yaml
charts/manager/Chart.yaml
charts/manager/templates/servicemonitor.yaml

This adds a ServiceMonitor to the Greenhouse Manager chart. This monitor will detect all service-proxy instances deployed to the organization namespaces and expose the metrics in the Central Clusters Prometheus.

feat(service-proxy): add servicemonitor to collect metrics

---

.github/workflows/docker-build.yaml

Images are not being build after go dependency updates, which only touch `go.mod`.

fix(docker-build): trigger build if go deps change

---

pkg/helm/manifest.go
pkg/helm/manifest_test.go

With 1.30 the NoKindMatchError is propagated by cli-runtime. Previously it was necessary to filter the error with string matching. https://github.com/kubernetes/kubernetes/pull/122569

refac(helm): match no CRD error instead of string

---

charts/demo/Chart.yaml
charts/demo/templates/alertmanager-pluginconfig.yaml
charts/demo/values.yaml
charts/greenhouse/Chart.lock
charts/greenhouse/Chart.yaml
charts/greenhouse/templates/pluginconfig-alerts.yaml

Updating the charts to reflect changes to the plugin.
- Assigning a unique name for the alerts plugin in the demo namespace.
- Adapt the Slack route configuration to new structure
- [ x ] 🐛 Bug Fix
- [ x ] 🙅 no, because they aren't needed
- [ x ] 🙅 no documentation needed
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my code

fix(charts/alerts): unique plugin name; align slack config

---

pkg/admission/teamrolebinding_webhook.go
pkg/admission/teamrolebinding_webhook_test.go

The cluster existence check has been removed from TeamRoleBinding Admission. With the clusterSelector it cannot be ensured that this always matches. The controller is returning appropriate events and errors during reconciliation. The existence check blocks editing if the cluster no longer exists.

fix(teamrbac): Remove cluster existence check

---

ui/.gitignore
ui/cluster-admin/package-lock.json
ui/cluster-admin/package.json
ui/cluster-admin/src/hooks/useApi.ts
ui/plugin-admin/package-lock.json
ui/plugin-admin/package.json
ui/plugin-admin/secretProps.template.json
ui/plugin-admin/src/plugindefinitions/hooks/useApi.ts
ui/secret-admin/package-lock.json
ui/secret-admin/package.json
ui/secret-admin/src/hooks/useApi.ts

This sets default verbosity on UI API calls to `silent`
We use `GET` request to check if a user is authorized. We do not need a defaulted verbose output for failures.

fix(ui): remove default verbose output on api calls

---

charts/greenhouse/Chart.lock
charts/greenhouse/Chart.yaml
charts/idproxy/Chart.yaml
charts/idproxy/templates/service.yaml
charts/idproxy/templates/servicemonitor.yaml

Adds a ServiceMonitor to collect the idproxy metrics.
Also adds the metrics endpoint to the idproxy service.
- Related Issue #286

feat(idproxy): collect metrics from exposed port

---

.github/workflows/docker-build.yaml
Dockerfile.dev-env
dev-env/docker-compose.yaml
dev-env/network-host.docker-compose.yaml
docs/contribute/local-dev.md

This fixes the failing builds for `Dockerfile.dev-env` and `Dockerfile.dev-ui` after https://github.com/cloudoperators/greenhouse/pull/353
- `dev-ui` needs to be build locally
- `dev-env` still had a reference to `plugin.yaml` file refactored to `plugindefinition.yaml` by https://github.com/cloudoperators/greenhouse-extensions/pull/225

fix(dev-env): Failing docker builds

---

docs/contribute/local-dev.md

This removes the landing page link to local-dev setup from the website home.

fix(website): Remove local-dev link from homepage

---

dev-env/docker-compose.yaml
dev-env/network-host.docker-compose.yaml

With the move the exposed port changed to 3005. The KubeConfig still refers to 8090. 
Changes the `kubectl apply` during bootstrap to match the folder structure.

fix(dev-env): use 8090 for envtest, fix bootstrap

---

pkg/apis/greenhouse/v1alpha1/event_types.go
pkg/apis/greenhouse/v1alpha1/teamrolebinding_types.go
pkg/controllers/teamrbac/teamrolebinding_controller.go

If the cluster cannot be found by name the ClusterListEmpty status should be updated. Previous the reconcile failed without updating the status. Ready condition stayed true

fix(teamRBAC): ensure status updated on cluster not found

---

dev-env/docker-compose.yaml
docs/user-guides/plugin/development.md

Add mounting an additional folder `/helm-charts` to the dev-env where plugin developers can place a `*.tgz` file to make use of a local chart instead of a hosted chart.

feat(dev-env) add mounting a local helm chart

---

pkg/controllers/organization/rbac_controller_test.go
pkg/controllers/organization/suite_test.go
pkg/test/assert.go
pkg/test/resources.go

Refactoring to use the `test.TestSetup` and introduce a dedicated helper to create Org objects

refac(org): use test.Setup for org rbac controller tests

---

pkg/admission/team_webhook.go

The Greenhouse controller manager crashed due to concurrent writes to a map.
The map in question was in the global scope.
```bash
fatal error: concurrent map writes
goroutine 145342 [running]:
github.com/cloudoperators/greenhouse/pkg/admission.validateGreenhouseLabels(0xc000b81040, {0x26c1910, 0xc000b8d530}, {0x26d2e80, 0xc00011b050})
/workspace/pkg/admission/team_webhook.go:75 +0x165
github.com/cloudoperators/greenhouse/pkg/admission.ValidateUpdateTeam({0x26c1910?, 0xc000b8d530?}, {0x26d2e80?, 0xc00011b050?}, {0x17d5a7a?, 0xc000b81040?}, {0x26a98d8?, 0xc000b81040?})
/workspace/pkg/admission/team_webhook.go:62 +0x4c
github.com/cloudoperators/greenhouse/pkg/admission.(*customValidator).ValidateUpdate(0xc000b81040?, {0x26c1910?, 0xc000b8d530?}, {0x26a98d8?, 0xc000b81180?}, {0x26a98d8?, …
```

fix(team_webhook): concurrent write on map

---

go.mod

The toolchain directive is utterly brocken and picky about the go version used and causes lots of conflicts and breakges in our pipelines.

fix: remove toolchain from go.mod

---

pkg/controllers/cluster/bootstrap_controller_test.go
pkg/controllers/cluster/direct_access_controller_test.go
pkg/controllers/cluster/headscale_access_controller_test.go
pkg/controllers/cluster/status_controller_test.go
pkg/controllers/cluster/suite_test.go
pkg/test/resources.go
pkg/test/util.go

This change separates the tests from each other. Each controller runs in its own namespace, own remote devenv. Resources are cleaned up after each suite.
This should reduce flakiness in the tests and reduce test resources from one suite showing in the logs of another suite.
Also removes deletion logic for Secrets, as devenv does not include controllers for build-in resources

fix(clusters): remove test flakiness

---

pkg/controllers/plugin/helm_controller.go

This fixes that the wrong variable was used to retrieve the error message of helm reconciliation failures.

fix(helmController): expose error on helm reconcile failure"

---

pkg/apis/well_known.go
pkg/controllers/plugin/helm_controller.go
pkg/controllers/plugin/pluginpreset_controller.go

- ensure PluginPreset is only reconciled when owned Plugins are changed, remove additional watch on Plugin LabelChanged
- remove Watch on deprecated Label from HelmController
- fix: ensure only plugins that refer to a cluster are queued on change

fix(plugin): reduce watches on Plugin & PluginPreset

---

ui/cluster-admin/src/components/OnBoardCluster.tsx
website/hugo.yaml

- The Cluster Onboarding docs page was not yet pointed to Github Pages.
- Updated the base link for our documentation to Github pages

fix(dashboard): point docs to github pages

---

charts/manager/alerts/proxies.alerts

This changes the alert to 
- only alert on `4xx` and `5xx` request responses. 
- calculate the percentage of failing requests to the sum of all requests

Fix(proxy): Fixes the proxy alert expression

---

pkg/test/env.go

The DEX CRDs are required by the `OrganizationDexController`. This ensures all possible CRDs required by Greenhouse are deployed to the devenv. 

feat(dev-env): add DEX crds to installed CRDs

---

pkg/admission/plugin_webhook_test.go
pkg/admission/teamrole_webhook_test.go
pkg/admission/teamrolebinding_webhook_test.go
pkg/admission/webhook_suite_test.go

This moves the TeamRole & TeamRoleBinding webhook tests to use `test.SetupTest` to create a dedicated namespace & resources for each test.

refac(teamrbac): use test.TestSetup for webhook tests

---

.github/workflows/unit-tests.yml
Makefile

Split the make fmt command into fmt and lint.
The GH Action should only lint, as running format will hide potential formatting, import order findings.

feat(makefile): split fmt into fmt and lint

---

pkg/rbac/role.go

allow OrgAdmins to view secrets, configmaps & workload ressources in their namespace

feat(rbac): allow OrgAdmins to view secrets, configmaps & workload res

---

pkg/internal/local/klient/kind.go
pkg/internal/local/setup/cluster.go

During the usage of `greenhousectl dev setup` the namespace `greenhouse` creation for the central / admin cluster was done using `kubectl create namespace ....` command, which uses the current-context. 
`KinD` CLI always sets the current-context and if the cluster exists we make sure to set the current-context of the `KinD` cluster being used.
But the pkg `https://github.com/vladimirvivien/gexe` uses a dedicated session for each shell command that is executed in the dev setup process. The current context of `KinD` will not be made available in the next session as the previous session is destroyed.
To prevent applying to wrong context `--kubeconfig` parameter is passed to the command, retrieved from the previous step during cluster creation.

(fix): create namespace using kubeconfig

---

pkg/controllers/plugin/helm_controller.go
pkg/controllers/plugin/plugin_workload_status_controller.go
pkg/controllers/plugin/pluginpreset_controller.go
pkg/controllers/plugin/util.go

this PR fixes the duplicate message in workload status controller / refactors ComputeReadyCondition 

fix(plugin) workload status controller duplicate message / ComputeReadyCondition

---

pkg/admission/utils.go

This redacts secret data in admission request logging
- Related Issue  https://github.com/cloudoperators/greenhouse/issues/415
No direct way to test controller output logs with Ginkgo. Ginkgo swallows logs when testing.

fix(audit-logs): Redact secret data

---

pkg/internal/local/klient/kind.go

`namespace` apply must use the cluster kubeconfig otherwise `kubectl` relies on current context leading to apply of resource to wrong cluster.

fix(dev-env): provide kubeconfig param for namespace apply

---

cmd/greenhouse/controllers.go
pkg/controllers/organization/organization_controller.go
pkg/controllers/organization/organization_controller_test.go
pkg/controllers/organization/rbac_controller_test.go
pkg/controllers/organization/suite_test.go
pkg/test/resources.go
test/e2e/controllers.go

This PR refactors NamespaceController into OrganizationController. It adds Org Admin Team reconciliation into the OrganizationController. Org admin team's purpose is then to be used by TeamMembershipController to create TeamMemberships.
- Closes #478 
Added integration tests checking the logic of OrganizationController updater.
Run ginkgo tests in `greenhouse/pkg/controllers/organization` directory.

refac(org): controller reconciles namespace and team

---

charts/greenhouse/Chart.lock
charts/greenhouse/Chart.yaml
charts/manager/Chart.yaml
charts/manager/alerts/operator.alerts
charts/manager/alerts/proxies.alerts

- Proxy alerts were firing too frequently for the CORS proxy, because normal users will not have authorization to see secrets.
- increased duration for token expiry from less than 1h to less than 20h, as the controller should refresh once the validity is less than 20h
- added missing `for` conditions 

fix(alerting): add for conditions, ignory proxy unauth(z) err

---

charts/manager/alerts/operator.alerts
pkg/controllers/plugin/helm_chart_test_controller.go

This PR removes the requeue logic from the helmChartTestcontroller when the helmStatus is "not deployed". As, a new reconciliation will be automatically triggered when the HelmReleaseStatus changes to "deployed".

Improve helm chart test controller

---

pkg/controllers/cluster/status_controller.go
pkg/controllers/plugin/plugin_workload_status_controller.go

ClusterStatus and WorkloadStatus reconciler
now ignore if the Cluster/Plugin was deleted in
the meantime

fix: ignore NotFound errors

---

pkg/controllers/plugin/pluginpreset_controller.go
pkg/controllers/plugin/pluginpreset_controller_test.go

Add skipping of updating if plugin preset has not been changed.
- Closes #437

feat(pluginpreset) Skip updating when plugin is not different (#437)

---

docs/reference/api/openapi.yaml
pkg/apis/greenhouse/v1alpha1/plugin_types.go
pkg/controllers/plugin/pluginpreset_controller.go
pkg/controllers/plugin/pluginpreset_controller_test.go
pkg/helm/helm.go

The equality check ran into nil pointer if one of the `optionValue.Value` was nil. This came up when `optionValues.ValueFrom` is used.

fix(pluginpreset): handle valueFrom in shouldSkipPlugin

---

pkg/controllers/plugin/helm_chart_test_controller.go

With this PR, the Helm Chart Tests won't run from the `helmChartTestController` when the plugin is disabled in the spec. 
fixes https://github.com/cloudoperators/greenhouse/issues/550

fix(helmChartTestController): Don't run test when plugin is disabled

---

cmd/service-proxy/proxy.go

If a Plugin is failing the service-proxy was triggered for each update to the Plugin's status
- only requeue if secret resourceversion changed
- only requeue if plugin generation/ label changed

fix(service-proxy): only enqueue if watched resource changed

---

Dockerfile.dev-env
Makefile

fix(build) dev-env build, platform auto detect

---

pkg/helm/helm_test.go
pkg/helm/values.go
test/e2e/plugin_lifecycle_test.go

This provides `common.DNSDomain` as `global.greenhouse.baseDomain` in the PluginValues injected to each Plugin
- [Related Issue](https://github.com/cloudoperators/greenhouse/issues/407)

feat(plugin): Provide base domain as Plugin value

---

docs/user-guides/plugin/plugin-tests.md

This PR adds documentation for https://github.com/cloudoperators/greenhouse-extensions/pull/389. 
resolves https://github.com/cloudoperators/greenhouse-extensions/issues/341

docs(plugin): enhance Plugin ChartTest documentation

---

docs/reference/api/openapi.yaml
pkg/apis/greenhouse/v1alpha1/plugin_types.go
pkg/common/url.go
pkg/common/url_test.go
pkg/controllers/plugin/remote_cluster_test.go
pkg/controllers/plugin/suite_test.go
pkg/controllers/plugin/util.go
pkg/helm/helm.go
pkg/helm/helm_test.go

This fixes 
- URL creation of exposed services to use the `plugin.Spec.ReleaseNamespace` instead of the `plugin.GetNamespace()`
and removes
- the utility method `GetReleaseNamespace()` to directly use `.Spec.ReleaseNamespace`

Fix(service-proxy): use release namespace

---

pkg/controllers/plugin/remote_cluster_test.go
pkg/helm/diff_test.go
pkg/helm/suite_test.go

Simple fix for plugin's outdated GetReleaseNamespace reference. Now it needs to be plugin.Spec.ReleaseNamespace.
Changed in https://github.com/cloudoperators/greenhouse/pull/576

fix: change outdated plugin release namespace references

---

docs/user-guides/plugin/plugin-deployment.md
pkg/controllers/plugin/helm_controller.go
pkg/controllers/plugin/remote_cluster_test.go
pkg/test/fixtures/chartWithExposedService/Chart.yaml
pkg/test/fixtures/chartWithExposedService/templates/services.yaml
pkg/test/fixtures/chartWithExposedService/values.yaml

This PR fixes the bug with incomplete URLs generated for exposed services, when a plugin is deployed to the central cluster. It also adds docs describing exposed services in plugin deployment.
- Fixes #324 
I added a test checking that HelmController correctly lists URLs for exposed services in plugin status, and a test that confirms the error is reflected on plugin status condition when URLs cannot be generated due to missing cluster name.

Fix: prevent incomplete urls for exposed services in plugin

---

pkg/admission/organization_webhook.go
pkg/admission/organization_webhook_test.go

This PR denies the deletion of Organization CRs in the Organization Webhook, regardless of dependencies.
- Closes #541 
I've added a unit test to check if webhook denies the deletion. I've tested the deletion on a cluster, but decided not to commit the integration test.

feat(organizationwebhook): deny deletion of organization

---

Makefile
pkg/test/env.go
test/e2e/controllers.go
test/e2e/onboard_self_test.go
test/e2e/plugin_lifecycle_test.go
test/e2e/suite_test.go
test/e2e/webhooks.go

This PR ensures that e2e(s) are run with build tags and no longer runs with unit tests

ehancement(e2e): Run E2e with build tags

---

docs/user-guides/plugin/plugin-deployment.md
pkg/common/url.go
pkg/common/url_test.go
pkg/controllers/plugin/remote_cluster_test.go

We currently generate URLs for exposed services without boundary to the first subdomain. The following patter is used:
```
$https://$service-$namespace-$cluster.$organisation.$basedomain
```
As per https://github.com/cloudoperators/greenhouse/issues/78 this fails when the first subdomain exceeds 63 characters.
This PR 
- caps the first subdomain to 63 chars by appending a hash value if exceeding
- changes the order of the first subdomain to `$service--$cluster--$namespace`, since the hashing might eat up the namespace and it is considered the least important information on the URL.
[
- Fixes # (issue)](https://github.com/cloudoperators/greenhouse/issues/78)
Please describe the tests that you ran to verify your …

feat(service-proxy): Cap URL subdomain at 63 chars

---

cmd/service-proxy/proxy.go

Adds a debug log to the service-proxy to get a hold on current cluster routes.

fix(service-proxy): Get route logging

---

cmd/service-proxy/instrumentation.go
cmd/service-proxy/proxy.go
cmd/service-proxy/proxy_test.go
pkg/common/url.go

We introduced a regression [with changing the order of parameters](https://github.com/cloudoperators/greenhouse/commit/9a049d83879e41e6e0009f9fa7f910ca33c31308#diff-d3666ab886c1a27806b6d26677a42b167e6816af8c07fcade3bb8328f115f7dc) in the service-proxy host.
This PR hotfixes this regression, but we still need a better permanent solution

fix(service-proxy): Correctly decompose host

---

pkg/controllers/cluster/direct_access_controller.go
pkg/controllers/cluster/headscale_access_controller.go

Cluster metrics were not updated when something went wrong during reconciliation. This resulted in the appropriate alert not being sent by Prometheus.
- Closes #519
- Fixes #519

fix(cluster) Cluster's metrics is updated (#519)

---

.github/workflows/helm-push.yaml

This builds the greenhouse-ui helm chart separately from the greenhouse umbrella chart.

feat(gh-action): Build UI helm chart separately

---

charts/dashboard/Chart.yaml
charts/dashboard/ci/test-values.yaml
charts/dashboard/templates/dashboard-props-cm.yaml
charts/dashboard/templates/deployment.yaml
charts/dashboard/templates/ingress.yaml
charts/dashboard/templates/service.yaml
charts/dashboard/values.yaml

Adds new charts for ui with different resource naming until the decoupling from backend is done. The UI part is going to be deployed in an other release and this avoids resource naming collision for now.

feat(ci): adds new charts for ui with different resource naming until the decoupling from backend is done

---

pkg/controllers/organization/service_proxy_controller.go
pkg/controllers/organization/service_proxy_controller_test.go
pkg/controllers/organization/suite_test.go

In this PR the controller returns without error when the service-proxy plugin definition is missing and watches for changes in service-proxy plugin definition to create or update service-proxy plugin for organizations.
- Closes #542 
1. Spin up the local environment without any resources
2. Add an organization
3. See that ServiceProxyController logs missing service-proxy plugin definition and returns without error
4. Add the service-proxy PluginDefinition
5. See that ServiceProxyController is triggered and adds service-proxy plugin for organization

fix(service-proxy-controller): watch service-proxy plugin definition

---

charts/manager/crds/kustomization.yaml

The ClusterKubeconfigs CRD was not added to the kustomization.yaml

fix: ClusterKubeconfigs not registered in kustomization

---

pkg/rbac/role.go

Organization members should be able to view TeamRoles and TeamRoleBindings. 

fix(rbac): adjust access on TeamRole & TeamRoleBindings for org members & cluster admins

---

pkg/admission/organization_webhook.go
pkg/admission/organization_webhook_test.go

This reverts commit ffeaae094f6541b9407f86a86393c6a36031370a.
Besides Greenhouse Admins, nobody is allowed to delete Organization resources. With the revert it will possible again to test cleanup logic etc.
@abhijith-darshan regarding what we have talked about in the office yesterday.
The RBAC on the Organization is defined here: https://github.com/cloudoperators/greenhouse/blob/main/pkg/rbac/clusterrole.go

Revert "feat(organizationwebhook): deny deletion of organization (#610)"

---

charts/manager/alerts/operator.alerts

This pull request adds an alert for failing Helm Chart tests. The alert is triggered when the Helm Chart test has been failing for the last 15 minutes. The alert includes information about the plugin, namespace, and cluster of the remote cluster.
pre-requisite for https://github.com/cloudoperators/greenhouse-extensions/issues/447

Add alert for failing Plugin Helm Chart tests

---

pkg/admission/plugin_webhook.go

In case a value is invalid, the error should show the invalid value rendered as a string instead of the []byte.

fix(plugin): webhook errors contained []byte value

---

.github/renovate.json
Makefile

fix(makefile) fix renovate version substitution

---

pkg/controllers/organization/dex_controller.go

With the removal of checking if an Organization has OIDC configured [here](https://github.com/cloudoperators/greenhouse/pull/650/files#diff-9bd930233c1238c12ec8fb701985605cd422789cff96439d72cab2f73903ee1aL70-L73) it is necessary to use the added predicate `clientutil.PredicateHasOICDConfigured()` also in the `For(Organization)`.
Else the controller is running into nil pointer here: https://github.com/cloudoperators/greenhouse/blob/28e29288de22d6747d24ba6352cd2106f1dc6022/pkg/controllers/organization/dex_controller.go#L99-L106

fix(dexcontroller): ensure orgs without oidc are not reconciled

---

pkg/controllers/teamrbac/teamrolebinding_controller.go
pkg/controllers/teamrbac/teamrolebinding_controller_test.go

reconciliation failures for RoleBindings did not mention for which Namespace they failed.
With this change both, events and PropagationStatus, will contain the error message describing
why the reconciliation failed
- Related PR #667, needs to be rebased after merging the standardisation

feat(teamrbac): show failing namespaces

---

.github/workflows/ci-pr-title.yaml

This PR is adding a new action to run on every PR to enforce semantic headers, this is a pre-requisite for CHANGELOG generation. Shared action is not yet available, but In-progress

feat(actions): enforce semantic pr title

---

.github/workflows/ci-pr-title.yaml

This adds a new valid `type` for PR titles: `docs`

fix(ci): add docs as type

---

docs/user-guides/cluster/onboarding.md

This aims to better define and outline the permission scopes needed to onboard a `Cluster` to Greenhouse
- Closes #539

docs(clusters): improve cluster onboarding documentation

---

cmd/service-proxy/proxy.go

Reverts cloudoperators/greenhouse#557
The service-proxy needs to be triggered upon changes to the Plugin's status. Since the status contains the information required to proxy the request to the correct service & port. 
With the predicates, changes to the status were not reconciled

fix(service-proxy): revert only enqueue if watched resource changed

---

charts/manager/templates/webhooks.yaml
hack/helmify

This adds a `yq` command to the helmify script to add a namespaceSelector to the secret webhooks.
File is reformatted by `yq`, this is a one-time operation

feat(utils): add namespace selector to greenhouse secret webhooks

---

pkg/controllers/organization/dex_controller.go

Adds empty status func to dex controller to prevent endless reconciliation

fix(organizations): prevent dex controller from endless reconcile

---

pkg/admission/plugin_webhook_test.go
pkg/admission/teamrole_webhook_test.go
pkg/test/resources.go
pkg/test/setup.go

These helper to instantiate Test Resources should be available for the integration and e2e tests.
The E2E tests do not use `test.TestSetup` and thus the usage with TestSetup has been extracted.

feat(core): make test resource funcs usable without test.TestSetup

---

pkg/controllers/plugin/helm_controller.go

each reconciliation the HelmReconcileFailed condition was set to false, if the PluginDefinition is found. Only a successful reconciliation of the plugin should be able to flip the status

fix(plugins): ensure HelmReconcileFailed condition is idempotent

---

pkg/controllers/teammembership/teammembership_updater_controller.go

SCIM API requests are rate-limitted
Jitter will help to spread the requeues better

fix(teammemberships): add jlitter to requeue to spread load

---

.github/CODEOWNERS

Currently changes to `e2e` folder requires Administrator approval. This PR ensures that e2e is part of @cloudoperators/greenhouse-backend approval

chore(ci): adds e2e to CODEOWNERS

---

pkg/admission/secret_webhook.go
pkg/admission/secret_webhook_test.go
pkg/cmd/cluster_bootstrap.go

- `greenhousectl cluster boostrap` enforces of the 40 character limit and no `--` in the ClusterName
- the secret webhook is enforcing the name validation for type `greenhouse.sap/kubeconfig`. the func are re-used from cluster webhook: https://github.com/cloudoperators/greenhouse/blob/4ff77ed17b7bd8354415982de26748849044cab1/pkg/admission/cluster_webhook.go#L91-L97

feat(greenhousectl): validation of cluster name during onboarding

---

docs/contribute/plugins.md
docs/getting-started/core-concepts/_index.md
docs/user-guides/organization/creation.md
docs/user-guides/plugin/local-plugin-development.md

Fixes some broken links in the documentation.

chore(docs): fix broken links

---

pkg/controllers/cluster/bootstrap_controller_test.go
pkg/controllers/cluster/cluster_controller.go
pkg/controllers/cluster/cluster_controller_test.go
pkg/controllers/cluster/kubeconfig_controller.go
pkg/controllers/cluster/kubeconfig_controller_test.go
pkg/controllers/cluster/status_test.go
pkg/controllers/organization/suite_test.go
pkg/controllers/plugin/pluginpreset_controller.go
pkg/controllers/plugin/pluginpreset_controller_test.go
pkg/controllers/plugin/remote_cluster_test.go
pkg/helm/helm_test.go
pkg/test/fixtures/myChartWithCRDs/crds/greenhouse.sap_teams.yaml
pkg/test/resources.go
pkg/test/setup.go
pkg/test/util.go

This addresses several problems that surfaced after the `MustDeleteCluster` assertion was flipped to ensure it waits until the Cluster is deleted.
This should also address the issue of seeing error logs in a test for an unrelated cluster.
Notable changes:
- PluginPreset will not reconcile a Plugin for a Cluster that has been marked as deleted
- Cluster will succeed with deletion if KubeConfig is not valid

fix(tests): addresses flakiness in tests, fixes failures due to twisted test assertion

---

docs/user-guides/plugin/plugin-management.md
pkg/admission/pluginpreset_webhook.go
pkg/admission/pluginpreset_webhook_test.go
pkg/controllers/plugin/pluginpreset_controller_test.go

I implemented validation in the webhook to prevent the deletion of plugin presets when the greenhouse.sap/prevent-deletion annotation is present.

feat(pluginpresets): deletion protection for plugin preset

---

.github/workflows/ci-e2e-test.yaml

Runs greenhouse e2e using shared action from `cloudoperators/common`
- Closes #725

feat(ci): runs e2e using shared action

---

.github/workflows/codeql.yaml

Skip `CodeQL` run when only `docs/**` is changed in a PR

fix(ci): codeql not triggered when docs changed in a PR

---

pkg/clientutil/predicates.go
pkg/controllers/propagation_reconciler.go
pkg/controllers/propagation_reconciler_test.go

The Propagation Controller is deprecated, so right now we need only clean up and remove finalizer.
The tests have not been written so we should focus to make very carefully code review. 
- Closes #777 

feat(controller): deprecation of propagation controller

---

pkg/controllers/propagation_reconciler.go

Clusters which are not accessible block the deletion. This skips clusters which cannot be accessed.

fix(core): skip non-ready clusters during propagation reconciliation

---

pkg/lifecycle/reconcile.go
pkg/lifecycle/reconcile_test.go

This PR addresses prevents the deletion scenario where if non-cleanup finalizers were set on the greenhouse custom resource, the reconciler slipped into `ensureCreated` phase.
- Closes #896 #895 
By having additional finalizers other than the common `CleanUpFinalizer` the reconciler should not enter into `ensureCreated` phase

fix(controller): prevent lifecycle reconcile to enter creation phase if deletionTimestamp is set

---

pkg/controllers/plugin/plugin_controller.go

The plugin controller flaps between True and False for `HelmReconcileFailed` condition as it is initialized in the beginning to be `False` and then later set to `True` due to reconciliation errors.
We need to avoid this so that the reconcile doesn't go into an endless loop

fix(plugins): prevent infinite reconciliation in plugins

---

pkg/controllers/organization/dex.go
pkg/controllers/organization/organization_controller_test.go

the greenhouse oauth2client is reused for the dashboard it should include all org redirects
the old logic removed any redirects not specified on the greenhouse org

fix(dex): do not remove org redirects on default oauthclient

---

pkg/controllers/organization/dex.go
pkg/controllers/organization/organization_controller_test.go

The redirect URI for the org was missing the `.dashboard.` subdomain. 

fix(dex): add dashboard subdoamin to org redirect URI

---

pkg/helm/helm.go

The Chart Testing has no timeout set by default. This PR sets at least the default timeout used for the [HELM CLI](https://github.com/helm/helm/blob/9fad3cd907012122465ae46cd340dd637ed429ea/pkg/cmd/release_testing.go#L97) 
This is to avoid that a Chart Test that retries on failure does not block the Plugin controller.

fix(plugins): set timeout for helm releasetest actions

---

PROJECT

The additional domain in the group name and path for the CRD types is redundant and not used.

fix(core): remove redundant domain from group for ClusterKubeconfig

---

pkg/controllers/cluster/cluster_status.go

Onboarding cluster with `kubeconfig` involved RBAC management by `Greenhouse` and hence `Ready` condition was based on only the `kubeconfig` validation.
With OIDC onboarding RBAC management was delegated to the client as the RBAC needed to exist beforehand.
This involved changing the `Ready` condition to ensure `AllNodesReady` condition to be `True`.
However this introduced a regression where `Ready` condition reported `False` when one of the nodes in the client cluster was not `Ready`.
This PR reverts the logic to compute ready condition based on kubeconfig validity only and fine grained status computing will be handled in follow-up issues. #1034 and #1035

fix(clusters): revert cluster ready condition

---

pkg/controllers/cluster/kubeconfig_controller.go
pkg/controllers/cluster/kubeconfig_controller_test.go

The `kubeConfig` key is only used when onboarding Cluster with kubeconfig. When using OIDC this is not present.
Using the `greenhouseKubeConfig` will work for both cases, since this is the kubeconfig that is managed by Greenhouse

fix(clusterkubeconfigs): use greenhouse-manged kubeconfig

---

internal/clientutil/predicates.go
internal/controller/teammembership/teammembership_updater_controller.go

previously the teams were only reconciled if the orgs generation changed.
this commit makes sure that the teams are reconciled if the org's state for scim api access changes to true.

fix(teams): reconcile teams if scim api access is ready

---

charts/greenhouse/Chart.yaml
charts/greenhouse/templates/organization-secrets.yaml

`OwnerReferences` without `UID` are invalid and should be handled either programmatically or with `helm lookup`

fix(charts): remove organization owner reference on auth secrets

---

charts/greenhouse/Chart.lock
charts/greenhouse/Chart.yaml
charts/idproxy/Chart.yaml
charts/idproxy/templates/deployment.yaml
charts/idproxy/values.yaml
cmd/idproxy/main.go

Making the `keepUpstreamGroups` configurable on the idproxy. This can then be used for applications hidden behind the idproxy after #701 is fully implemented to use idproxy for auth instead of upstream idp.

feat(idproxy): make keepUpstreamGroups configurable

---

charts/dashboard/templates/dashboard-props-cm.yaml
charts/dashboard/values.yaml
dev-env/ui.values.yaml
internal/local/setup/dashboard.go

- Removes 'mockAuth' from the default appProps.json (deprecated in juno)
- Removes 'environment' from charts/dashboards (deprecated in juno, [commit](https://github.com/cloudoperators/juno/pull/706/commits/15de11203007c3c9e46002b9b81cf2f222ed6f8b))
Fixes #1048

fix(e2e): removes deprecated fields from the appProps.json creation

---

cmd/greenhouse/main.go

In case we are running in webhook only mode the leader election is not required, also it will clash with the leader election of the controller deployment.

fix(core): disable leader election in webhook-only mode

---

dev-env/dev.config.yaml

When running local setup or E2E tests, there is an error thrown: `Error from server (NotFound): configmaps "kube-root-ca.crt" not found`. Piping in the sleep command after context change fixes that problem.

fix(e2e): wait after context change in local setup

---

internal/test/resources.go

feat(tests): add options for ui only plugindefinitions

---

internal/local/commands/setup.go

- fixes the missing hostPath extra mounts for admin cluster
- Closes #1135 

fix(greenhousectl): reference the updated kind configuraton file for extra mounts

---

internal/clientutil/error.go
internal/controller/teamrbac/teamrolebinding_controller.go
internal/webhook/teamrole_webhook.go
internal/webhook/teamrole_webhook_test.go
internal/webhook/webhook_suite_test.go

After the Split of Controller and Webhook deployment the deletion of TeamRoles was failing due to a missing FieldIndex
This add the missing field indexing to the teamrole webhook setup. To avoid conflicts with already existing indices the IgnoreIndexerConflict(..) was added. The code does not expose a typed error, so in this case the check relies on the error's prefix

fix(teamroles): add fieldindex in webhook setup

---

.github/.goreleaser.yaml

Currently go releaser does not use the latest tag when multiple tags are pushed on the same commit.
https://github.com/cloudoperators/greenhouse/actions/runs/15585467918/job/43890439520#step:4:19
This will be the case when there was no bugfix between a release candidate and the final release.
tags can be sorted according to https://goreleaser.com/customization/git/

fix(ci): goreleaser sort tags by createordate

---

internal/controller/plugin/plugin_controller.go

fix(plugins): increase concurrent reconciles to 10

---

internal/controller/teamrbac/teamrolebinding_controller.go
internal/controller/teamrbac/teamrolebinding_controller_test.go

In case the clusterSelector did not match any clusters, the `RBACReady` condition was set to false, and then to true again at the end of the reconciliation.
Now there is an early-exit after cleaning up resources that ensures the condition is not flapping
- Fixes #1253 

fix(teamrolebindings): rbac Ready condition not flapping, removes unset condition

---

internal/controller/flux/plugin_controller.go
internal/controller/plugindefinition/plugindefinition_controller.go
internal/controller/plugindefinition/plugindefinition_controller_test.go

- Skip flux `HelmRepository` creation for UI `PluginDefinition` (Since there is no helm chart)
- Skip processing `Plugin` that reference UI `PluginDefinition` in plugin_to_flux controller

fix(plugindefinitions): skip helm repository creation for UI PluginDefinitions

---

internal/webhook/v1alpha1/plugin_webhook.go
internal/webhook/v1alpha1/plugin_webhook_test.go

The '.spec.releaseNamespace' should only be valdiated for plugins that are deployed in the central cluster

fix(plugins): fix central cluster namespace validation

---

internal/webhook/v1alpha1/plugin_webhook.go
internal/webhook/v1alpha1/plugin_webhook_test.go

fix(plugins): fix central cluster namespace validation (#1288)

---

api/v1alpha1/cluster_types.go
docs/user-guides/cluster/oidc_connectivity.md
docs/user-guides/cluster/onboarding.md
internal/cmd/cluster_bootstrap.go
internal/common/permissions.go
internal/controller/cluster/cluster_status.go
internal/controller/cluster/status_test.go

- Introduce two new `Cluster` status conditions: `PermissionsVerified` and `ManagedResourcesDeployed`
- Centralize permission-checking logic by moving it to `internal/common/permissions.go`
- Closes #1034
Validation checks for the `kubeconfig` secret setup have been added to the test suite. However, it is not currently possible to exercise the conditions when they evaluate to false: deleting resources such as the Namespace or ServiceAccount prior to reconciliation is ineffective, because the controller immediately re‑creates them and the validation conditions remain satisfied.

feat(clusters): add additional status conditions

---

internal/controller/flux/plugin_controller.go
internal/controller/flux/plugin_controller_test.go

fix(plugins): filter out secret-based plugin option values when generating helm values

---

e2e/plugin/scenarios/flux_controller.go
e2e/plugin/scenarios/plugin_controller.go
internal/controller/plugin/plugin_controller_flux_test.go
internal/controller/plugin/pluginpreset_controller_test.go
internal/controller/plugin/remote_cluster_test.go
internal/controller/plugin/suite_test.go
internal/helm/diff_test.go
internal/helm/helm_test.go
internal/test/resources.go
internal/webhook/v1alpha1/plugin_webhook_test.go

dedicated methods for value, valuefrom, template to avoid unnecessary setting of nil values.
method never allowed setting both value, valueFrom

refactor(tests): add helper for pluginoptionvalue with template

---

internal/controller/plugin/plugin_controller_flux.go
internal/flux/helm_release_builder.go

in the future this should be handled by annotations on the Plugin. Until this feature is implemented the current .suspend value should not be overwritten

fix(flux): ensure suspending a Flux release is honored

---

api/well_known.go
internal/controller/plugin/plugin_controller_flux.go
internal/helm/template.go
internal/helm/template_test.go
internal/helm/values.go

This PR enhances string templating for `PluginOptionValues` to support cluster-specific metadata. Cluster labels following the `metadata.greenhouse.sap/*` pattern are now automatically available in Plugin templates as `global.greenhouse.metadata.*` values. For example, a cluster labeled with `metadata.greenhouse.sap/region: eu-de-1` makes `{{ .global.greenhouse.metadata.region }}` available in Plugin templates, resolving to `eu-de-1`.
- Closes https://github.com/cloudoperators/greenhouse/issues/1361
Documentation will be added under different issue.

feat(plugins): add cluster metadata labels to global.greenhouse

---

api/well_known.go
internal/controller/plugin/plugin_controller.go
internal/webhook/v1alpha1/plugin_webhook.go
internal/webhook/v1alpha1/plugin_webhook_test.go
internal/webhook/v1alpha1/plugindefinition_webhook.go
internal/webhook/v1alpha1/plugindefinition_webhook_test.go

(chore): change enqueue request labels to cpd label
(chore): remove guard around delete
(cherry picked from commit 5a9a0bc426cf51dd424c13e4d2ec6c8035371152)

release(version): backport feat(plugins): rename PluginDefinition label to ClusterPluginDefinition label #1356

---

internal/webhook/v1alpha1/plugin_webhook.go

Skip releaseName validation for UI plugins

fix(plugins): skip releaseName validation for UI Plugins

---

api/v1alpha1/types.go
charts/manager/crds/greenhouse.sap_pluginpresets.yaml
charts/manager/crds/greenhouse.sap_plugins.yaml
docs/reference/api/openapi.yaml
internal/webhook/v1alpha1/plugin_webhook.go

Existing plugins without a `PluginDefinitionRef` will always have the referent `PluginDefinitionRef.Name` empty and we should avoid immutability check in such situation as the `MutatingWebhook` will ensure the required defaults for `PluginDefinitionRef` fields.
- Fixes #1441

fix(plugins): handle plugin definition ref name immutability bug

---

internal/controller/plugin/pluginpreset_controller.go

To avoid an early return before the Plugins are finally gone. Requeuing if any Plugins that were managed by the Preset were still listed for deletion

fix(pluginpresets): requeue until all plugins are gone

---

internal/controller/plugin/pluginpreset_controller_test.go
internal/test/resources.go

refactor(pluginpresets): configure test fixtures via code
