cloudoperators/greenhouse

- .reuse/dep5
- README.md
This PR should solve #18  and #17.
> fix: reuse compliance

- .github/workflows/docker-build.yaml
fix add QEMU to be able to build multi-platform images
fix disable gh cache for now
> fix(docker-build) disable cache in build action

- .github/renovate.json
add some update to renovate config
> feat(renovate) update renovate config

- pkg/cmd/cluster_bootstrap.go
> fix(greenhousectl) cleanup old logic

- ui/plugin-admin/package-lock.json
- ui/plugin-admin/package.json
Dependency is now fixed to prevent building problems connected to "lastest"
> [plugin-admin] Changed to Juno UI Components version 2.12.1

- ui/plugin-admin/package-lock.json
- ui/plugin-admin/package.json
Fixed all dependencies versions to ensure correct versions for the pipeline.
> [plugin-admin] Fixed all dependencies versions

- ui/plugin-admin/package-lock.json
- ui/plugin-admin/package.json
- ui/plugin-admin/src/components/Plugin.js
- ui/plugin-admin/src/components/PluginConditionIcon.js
- ui/plugin-admin/src/components/PluginDetail.js
- ui/plugin-admin/src/components/PluginList.js
- ui/plugin-admin/src/hooks/useAPI.js
Ressource Status Icon is now shown in the Details View. For a unified design language the icons are used like in cluster-admin.
> Plugin admin icon

- ui/plugin-admin/package-lock.json
- ui/plugin-admin/package.json
Set dependency utils to version 1.1.6
> [plugin-admin] update dependency utils

- .github/workflows/helm-lint.yaml
- Makefile
Closes #73 
Depends on #93 to not mess up `charts/**/templates/*.yaml`
> fix(gh-actions) Fix warnings

- .github/workflows/stale.yaml
> feat(gh-actions) add stale gh-actions

- Dockerfile.website
Update base image to `floryn90/hugo` for a more up-to date image
> fix(website) update base docker image

- charts/manager/crds/greenhouse.sap_plugins.yaml
- docs/reference/api/index.html
- docs/reference/api/openapi.yaml
- pkg/apis/greenhouse/v1alpha1/plugin_types.go
Prettify longer table headers as follows:
`PLUGINDEFINITION` -> `PLUGIN DEFINITION`
`RELEASENAMESPACE` -> `RELEASE NAMESPACE`
> prettify print columns header

- .github/workflows/helm-lint.yaml
- .github/workflows/helm-push.yaml
Implement GitHub Actions to package and push `Helm Charts` into `ghcr.io packages`
- Related Issue #13
> feat(gh-actions) helm package & publish

- .github/workflows/helm-push.yaml
- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
Bump the dependencies of the sub-charts. Also do not upload individual charts, as we package them in the umbrella greenhouse chart
> fix(charts): bump greenhouse chart dependencies

- pkg/controllers/plugin/helm_controller.go
Watching on both labels is required, as the deprecated `greenhouse.sap/plugin` will only be removed after reconciliation.
> fix(plugin): temporarily watch for old Plugin and new PluginDefinition labels

- charts/manager/templates/manager-role.yaml
- docs/reference/api/index.html
- docs/reference/api/openapi.yaml
- pkg/controllers/organization/dex_controller.go
- pkg/util/slices.go
I was doing that manually before, but this should be implemented and automated instead.
> reconcile oauth2client

- pkg/helm/helm.go
The drift detection should run either
- if the last transition of HelmDriftDetected is less than driftDetectionInterval
- if the last deployment was done less than driftDetectionInterval
> fix(helm): drift detection not run immediately after last deploy

- pkg/helm/helm.go
The release should be existing at this point. If the release does not exist, we can do an early return as it has to be reconciled.
> fix(helm): diff returns early if release not found

- pkg/controllers/plugin/pluginpreset_controller.go
The PluginPreset controller will be triggered when a Plugin was labelled the `greenhouse.sap/pluginpreset` Label.
This is convenience to make the PluginPreset controller aware that a Plugin that was previously not owned by the controller has been labelled. This is the case when a Plugin following the naming scheme of the PluginPreset already existed before the PluginPreset was created.
- [-] I have added tests that prove my fix is effective or that my feature works
> feat(preset): enqueue Preset if Plugin is labelled with Preset LabelKey

- .github/workflows/build-greenhousectl.yaml
The default token used in the action does not have permissions to write to the repository. Hence, it is not permitted to create a release. This will add the required permissions. 
> fix(goreleaser): add permissions to create release

- ui/secret-admin/__mocks__/client.js
- ui/secret-admin/__mocks__/fileMock.js
- ui/secret-admin/__mocks__/styleMock.js
- ui/secret-admin/package-lock.json
- ui/secret-admin/src/App.test.js
- ui/secret-admin/src/AppContent.tsx
Fixes testing on secre-admin view and adds a simple test.
> fix(ui): Fix secret-admin test

- ui/secret-admin/src/AppContent.tsx
- ui/secret-admin/src/components/SecretList.tsx
- ui/secret-admin/src/hooks/useWatch.ts
* allow creation without list permissions
* Do not list helm release secrets
> Fix(ui): secrets

- docs/user-guides/plugin/development.md
This PR adds a guide for a Plugin Developer on how to spin up the local development environment, onboard a kind cluster, generate a PluginDefinition from a Helm Chart and then deploy a Plugin to the kind cluster.
> docs(plugindev): add guide for local development

- .github/workflows/hugo.yaml
Bump the hugo version. This is the version we build the website with previously.
> chore(hugo): bump hugo version

- ui/team-admin/package-lock.json
- ui/team-admin/package.json
This PR:
- Fixes some typos appProps description
> fix(team-admin): make app public, remove stars from peerDependencies, some typos and version upgrade

- ui/dashboard/package-lock.json
- ui/dashboard/package.json
This PR:
- Fixes some typos in appProps description
> fix(dashboard): make app public, remove stars from peerDependencies and some typos

- ui/org-admin/package-lock.json
- ui/org-admin/package.json
This PR:
- Fixes some typos appProps description
> fix(org-admin): make app public, remove stars from peerDependencies and some typos

- ui/plugin-admin/package-lock.json
- ui/plugin-admin/package.json
This PR:
- Fixes some typos appProps description
> fix(plugin-admin): make app public, remove stars from peerDependencies and some typos

- ui/cluster-admin/package-lock.json
- ui/cluster-admin/package.json
This PR:
- Fixes some typos appProps description
> fix(cluster-admin): make app public, remove stars from peerDependencies and some typos

- ui/secret-admin/package-lock.json
- ui/secret-admin/package.json
This PR:
Set the MFE public
Remove unused peerDependencies
Patch version upgrade
> fix(secrets): make app public, remove unused peerDependencies

- ui/cluster-admin/package-lock.json
- ui/cluster-admin/package.json
- ui/dashboard/package-lock.json
- ui/dashboard/package.json
- ui/org-admin/package-lock.json
- ui/org-admin/package.json
- ui/plugin-admin/package-lock.json
- ui/plugin-admin/package.json
- ui/secret-admin/package-lock.json
- ui/secret-admin/package.json
- ui/team-admin/package-lock.json
- ui/team-admin/package.json
> Fix(uis): Update sass package to remove CWE-1050

- Dockerfile.dev-env
- Dockerfile.tailscale
> fix(Dockerfile) add apk upgrade to update packages

- .github/workflows/sync-issues-to-jira.yaml
> [feature] sync issues labeled jira

- ui/cluster-admin/README.md
- ui/dashboard/README.md
- ui/org-admin/README.md
- ui/plugin-admin/README.md
- ui/secret-admin/README.md
- ui/team-admin/README.md
This PR contains:
- add 'built wiht juno' badge in the app readmes with the self hosted svg
- Related Issue https://github.com/cloudoperators/juno/issues/59
> feat(apps) add 'built wiht juno' badge in the app readmes with the self hosted svg

- .github/CODEOWNERS
> feat(codeowners): change owner of workflows folder to core team

- ui/dashboard/package-lock.json
- ui/org-admin/package-lock.json
- ui/plugin-admin/package-lock.json
- ui/team-admin/package-lock.json
This PR contains:
- Upgrade of dedicated dependencies to fix vulnerabilities reported by audit
> chore(dashboard,orgAdmin,pluginAdmin,teamAdmin) fix vulnerabilities upgrading dependencies

- docs/architecture/high-level.md
- docs/architecture/monitoring.md
- docs/getting-started/overview.md
Empty image is present on some sites while the image is present in markdown.
> fix(website) fix assets link for website

- docs/architecture/high-level.md
- docs/architecture/monitoring.md
- docs/getting-started/overview.md
Empty image is present on some sites while the image is present in markdown.
> Fix/no ref/greenhouse website

- docs/architecture/high-level.md
- docs/architecture/monitoring.md
- docs/getting-started/overview.md
Empty image is present on some sites while the image is present in markdown.
> fix(website) assets links

- .github/workflows/hugo.yaml
> fix: website image by copying assets

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/container-image-retainer.yaml
Fixes typo in the image-retainer configmap
> fix(image-retainer): typo in configmap name

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-kube-monitoring.yaml
This is required for Plutono to authenticate against the Prometheus
> feat: add tlsConfig.caCert to greenhouse prom

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-kube-monitoring.yaml
> fix(monitoring): typo in values path

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-kube-monitoring.yaml
> fix: typo in values path

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-kube-monitoring.yaml
> fix(charts/greenhouse): set ingress annotations

- test/e2e/onboard_self_test.go
Imports in this file are always reformatted when running `make check`. 
> fix: import order

- .github/CODEOWNERS
The `/test` directory was not yet part of the codeowners.
> feat: add /test folder to codeowners

- ui/cluster-admin/package-lock.json
- ui/cluster-admin/package.json
- ui/cluster-admin/src/store.test.ts
This fixes the cluster-admin tests after code refactoring with https://github.com/cloudoperators/greenhouse/commit/6b43b82f362e136d659ccce1f845c7e0920e14e9
> fix(ui): cluster-admin update tests

- ui/dashboard/package-lock.json
- ui/dashboard/package.json
- ui/org-admin/package-lock.json
- ui/org-admin/package.json
This pins the versions of MFEs to all latest releases.
> feat(ui): Pin UI versions to latest releases

- pkg/admission/plugindefinition_webhook.go
- pkg/admission/plugindefinition_webhook_test.go
- pkg/apis/greenhouse/v1alpha1/plugindefinition_types.go
This PR fixes https://github.com/cloudoperators/greenhouse/issues/195
> fix(PluginDefinitions): Disallow defaulting of Option with Type Secret

- pkg/admission/teamrolebinding_webhook.go
Linting errors which did not come up with the [PR](https://github.com/cloudoperators/greenhouse/pull/362) that introduced them.
> fix(teamrbac): remove unused params

- charts/cors-proxy/Chart.yaml
- charts/cors-proxy/templates/deployment.yaml
- charts/cors-proxy/templates/service.yaml
- charts/cors-proxy/templates/servicemonitor.yaml
- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- cmd/cors-proxy/instrumentation.go
- cmd/cors-proxy/main.go
Added metrics:
- "http_requests_total"
- "request_duration_seconds"
- "response_size_bytes"
Metrics are exposed by default on 6543
ServiceMonitor added to collect the metrics
- Related Issue #286
> feat(cors-proxy): add and collect http metrics

- .github/workflows/hugo.yaml
Follow-up on renaming of `plugindefinition.yaml` in greenhouse-extensions.
> fix(hugo): get description from plugindefinition.yaml

- .github/workflows/deploy-githug-pages.yaml
> chore(hugo) upgrade version of hugo in the workflow

- .github/workflows/deploy-githug-pages.yaml
- .gitignore
- docs/_index.md
- website/package-lock.json
- website/package.json
> chore(hugo-npm-deps) add package.json with fix dependencies so we have the same setup locally and in the CI. Moved index file to docs

- .github/workflows/deploy-githug-pages.yaml
> fix(workflow-deploy-pages) run npm ci in the website folder

- .github/renovate.json
Wait 14 days for patch version  as well, not just for major and minor.
Configure helm v3 also to the waiting list.
> feat(renovate) add helm-go, wait 14 days for patch versions

- dev-env/docker-compose.yaml
- dev-env/network-host.docker-compose.yaml
- docs/contribute/local-dev.md
- test/e2e/README.md
This PR adds some concrete example on how to run and debug the greenhouse controller locally
> feat(docs): Improve docs on running greenhouse locally

- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/manager/Chart.yaml
- charts/manager/alerts/greenhouse-operator.alerts
- charts/manager/alerts/proxy-service.alerts
- charts/manager/templates/manager-prometheusrules.yaml
- charts/manager/values.yaml
This PR proposes an initial set of Prometheus alerts for the Greenhouse Controller, Webhooks and Proxy services.
- Related Issue #280 
> feat: intial alerts for controller, webhook & proxies

- charts/greenhouse/Chart.yaml
- charts/greenhouse/values.yaml
default value for predefinedFilters.
> fix(alerts): default value for predefinedFilters.

- cmd/cors-proxy/instrumentation.go
- cmd/service-proxy/instrumentation.go
- expose `http_request_duration_seconds` for idproxy
- rename `http_request_duration_seconds` & `http_response_size_bytes` for cors-proxy
> feat: add idproxy duration_seconds, unify metric names

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-alerts.yaml
> feat(charts/greenhouse) alerts slack routes by severity

- .github/workflows/check-changes-crd-api.yaml
Fix typo "genaration" --> "generation"
> fix: typo in CRD API bot commit message

- test/e2e/local-cluster/manager.values.yaml
> fix(e2e/kind): disable alerts for manager chart deployed to kind cluster

- pkg/scim/scim_client_mocks.go
The colon was introduced in #461, but should not be there. @Zaggy21 thanks for spotting this.
> fix: remove accidental colon from scim mock

- docs/user-guides/cluster/onboarding.md
This PR fixes a grammatical typo in documentation of onboarding a cluster.
> (fix): typo in user-guide onboarding docs

- docs/reference/api/openapi.yaml
- pkg/apis/greenhouse/v1alpha1/zz_generated.deepcopy.go
- test/e2e/plugin_lifecycle_test.go
- test/e2e/suite_test.go
Resolves linter warnings. The golangci config was introduced after the PR was created, thus not checked.
> fix: resolve linter warnings

- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/greenhouse/dashboards/controller-resources.json
- charts/greenhouse/dashboards/controller-runtime.json
- charts/greenhouse/dashboards/proxy-services.json
- charts/greenhouse/templates/configmap-plutono-dashboards.yaml
- charts/greenhouse/templates/plugin-plutono.yaml
> feat(greenhouse): plutono plugin and dashboards added

- website/hugo.yaml
Adds a mandatory legal disclosure link to our website.
> cleanup links; adds mandatory legal disclosure

- website/hugo.yaml
> Update icon in website

- pkg/controllers/cluster/metrics.go
- pkg/controllers/cluster/metrics_test.go
Reformat files to fix import order.
> fix: reformat imports

- .github/CODEOWNERS
> feat: update teams in codeowners

- pkg/internal/local/utils/utils.go
Go one stack up to show where the call to log came from.
> fix: set logger depth for local-setup

- ui/cluster-admin/package.json
- ui/dashboard/package.json
- ui/org-admin/package.json
- ui/plugin-admin/package.json
- ui/secret-admin/package.json
- ui/team-admin/package.json
Apps versions updated due to patch dependencies upgrade from renovate.
Related renovate PRs:
- #65
- #510
> chore(apps): upgrade versions due to patch dependencies upgrade

- pkg/admission/plugin_webhook.go
- pkg/admission/plugin_webhook_test.go
- pkg/admission/webhook_suite_test.go
- pkg/test/assert.go
- pkg/test/resources.go
- adds validation that .spec.pluginDefinition is immutable
- removes defaulting of ReleaseNamespace, as all Plugins are migrated by now
- use apimachinery to validate immutable
- returns all errors instead of early returning on first error
- refactor plugin webhook tests to use test.Setup
> feat(plugin): admission checks that PluginDefinition is immutable

- .github/workflows/ui-dashboard-image.yaml
This PR adds a workflow to build the Docker image for the Dashboard and push it to the GitHub Docker registry. The image is built whenever a PR is merged and is tagged with the current timestamp. The created image includes all dependent apps and can be used directly for deployment.
> feat(ui): add workflow to build the dashboard image

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-logshipping.yaml
This PR brings a basic configuration to collect and send all `AdmissionRequest` logs created by #465 to our log sink
> feat(logshipper): add config to send audit logs

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-logshipping.yaml
> fix(logshipping): use correct values for octobus

- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/greenhouse/templates/pluginconfig-logshipping.yaml
Copy paste error introducing a colon where it should not be.
> fix: remove superfluous colon

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-logshipping.yaml
Fix wrong syntax used for PluginOptions, missing fieldname for regex
> fix(logshipper): update config

- .github/workflows/ui-dashboard-image.yaml
Create dashboard UI image with a human readable timestamp and remove untagged images
> chore(ci): create dashboard image with a human readable timestamp and remove untagged images

- ui/dashboard/package.json
This PR bumps the version of dashboard (UI)
> feat(ui): bump dashboard version

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/pluginconfig-logshipping.yaml
The `.*` is misleading as the tag on the input. Only for the matches in the routing between filters & outputs the tags with wildcard make sense.
> fix(logshipping): remove suffix from audit input tag

- charts/ui/templates/deployment.yaml
This PR fixes the volume mounting of app props.
> fix(build): fix dashboard volumen mount

- docs/user-guides/plugin/plugin-tests.md
This pull request improves the documentation for plugin testing.
> docs(plugin): improve documentation for helm chart tests

- .github/workflows/docker-build.yaml
> fix(actions) build provenance already configured

- .github/workflows/pr-docker-build.yaml
- Dockerfile
- Dockerfile.dev-env
- Dockerfile.headscalectl
- Dockerfile.tailscale
- Dockerfile.tcp-proxy
- Makefile
> fix(build) rename makefile targets, PR build docker

- website/package-lock.json
- website/package.json
* https://github.com/cloudoperators/greenhouse/security/dependabot/45
> chore(deps): update website to remove vulnerability

- pkg/helm/helm.go
We avoid pulling a helm chart when it is already in cache.
- Closes #512
> refac(helm) Read Helm chart from cache (#512)

- README.md
This PR fixes outdated links and adds a link to the Greenhouse documentation and the architecture document in the README. 
- [] My changes generate no new warnings
> fix: update api reference link + add documentation link

- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/greenhouse/values.yaml
This is not a default value 😬 
> fix: remove org admin idp profile from chart

- Makefile
Bump the linter to the latest version.
Merge after #635, as this removes the code with new findings.
> feat(ci): bump golangci-lint to 1.61.0

- docs/reference/api/openapi.yaml
- pkg/apis/greenhouse/v1alpha1/conditions.go
- pkg/apis/greenhouse/v1alpha1/conditions_test.go
The call to `IsReadyTrue(..)` could result in a nil-pointer. This fixes the check and returns only True if the Ready condition exists and is set to true.
> fix(conditions): IsReadyTrue handles non-existing Ready condition

- docs/README.md
- docs/getting-started/core-concepts/_index.md
- docs/getting-started/core-concepts/clusters.md
- docs/getting-started/core-concepts/organizations.md
- docs/getting-started/core-concepts/plugins.md
- docs/getting-started/core-concepts/teams.md
The purpose of this PR is to provide a brief overview of some of the core components within Greenhouse.
> docs(core-concepts): adds descriptions for greenhouse core concepts

- .github/renovate.json
updates the tools version used in `Makefile`
> feat(renovate): update tools version in Makefile

- .github/renovate.json
> fix(renovate) rm custom managers

- .github/renovate.json
- Makefile
> fix(makefile) envtest variable

- charts/manager/crds/greenhouse.sap_pluginpresets.yaml
- docs/reference/api/openapi.yaml
- pkg/apis/greenhouse/v1alpha1/pluginpreset_types.go
adding Plugin Definition, Release Namespace and Ready as printcolumns
> feat(pluginpreset): additional printcolumns

- go.mod
- pkg/controllers/cluster/cluster_controller.go
- pkg/controllers/cluster/status.go
- pkg/controllers/cluster/util.go
- pkg/controllers/plugin/util.go
- pkg/test/util.go
Checking the actual `Bearertoken` validity from `kubeconfig` instead of relying on the cluster status.
> feat(clusterController): check actual token validity

- docs/getting-started/core-concepts/clusters.md
- docs/getting-started/core-concepts/plugins.md
- docs/getting-started/core-concepts/teams.md
This pull request fixes a typo in the documentation file.
> Fix typo in clusters.md

- .github/workflows/ci-e2e-test.yaml
This PR is depending on https://github.com/cloudoperators/common/pull/15
> feat(e2e): run e2e tests as actions

- .github/ISSUE_TEMPLATE/feature-request.yaml
> feat(config): update the feature issue template

- charts/manager/templates/kube-webhook-certgen.yaml
- charts/manager/values.yaml
provide annotations via helm values for cert job
> chore(template): adds cert job annotations to manager chart

- charts/manager/templates/webhooks.yaml
- hack/helmify
> fix(utils): incomplete label name

- docs/getting-started/core-concepts/plugins.md
Enhanced the Plugin documentation.
> docs(docs): update plugins.md

- docs/reference/api/openapi.yaml
- pkg/apis/greenhouse/v1alpha1/teamrolebinding_types.go
This fixes a bug introduced with PR #667 for issue 581. Only change the LastTransitionTime when the propagation status has changed.
- Related Issue #581 
> fix(teamrolebindings): fix LastTransitionTime setting

- .github/workflows/check-changes-crd-api.yaml
> fix(actions): crd api gen use PAT to trigger actions

- charts/greenhouse/Chart.yaml
- charts/manager/alerts/proxies.alerts
This alert will notify if the dexidp is running into 5xx errors
Closes #739 
> feat(idproxy): add alert for 5xx errors

- .github/workflows/ci-e2e-test.yaml
- e2e/kind-config.yaml
> fix(actions): migrate upload artifact to v4

- docs/user-guides/organization/creation.md
- pkg/admission/organization_webhook.go
- pkg/admission/organization_webhook_test.go
- pkg/controllers/cluster/kubeconfig_controller_test.go
- pkg/test/resources.go
The field mappedOrgAdminGroupID is mandatory for organizations.
- Closes #699 
> feat(organizations): mappedOrgAdminGroupID is mandatory for organizations

- pkg/controllers/plugin/helm_controller.go
The Message of `StatusUpToDateCondition` was only updated if setting the status did not succeed. 
This will ensure the condition does not retain an outdated message/reason.
> fix(plugins): clear message if StatusUpToDateCondition changes

- .github/workflows/ci-pr-title.yaml
add scope for changes to helm charts
> feat(ci): add charts as accepted pr title scope

- docs/contribute/new-controller.md
> docs(core): typo in controller contrib guide

- Makefile
- docs/reference/api/openapi.yaml
each commit of the  workflow triggers all workflows pinning the version to 'main' ensures that the workflow does not commit a version change
> feat(ci): pin openapi-spec to version 'main'

- .github/workflows/check-changes-crd-api.yaml
According to the [docs](https://github.com/EndBug/add-and-commit?tab=readme-ov-file#the-commit-from-the-action-is-not-triggering-ci) the token used to checkout the repository determines which token is used by `endbug/add-and-commit` to commit.
This makes that the repo is checked out with the PAT of Cloud Operator. The PAT used by `endbug/add-and-commit` is just used to lookup user info and can be the default user`
> fix(ci): checkout repo with PAT

- docs/reference/api/openapi.yaml
- pkg/apis/greenhouse/v1alpha1/teammembership_types.go
- pkg/controllers/teammembership/teammembership_updater_controller.go
- pkg/scim/scim_client.go
- pkg/scim/scim_client_test.go
- do not supress error on getting individual members from SCIM
- report status for inactive/malformed members
> fix(teammemberships): improve error handling

- .github/workflows/docker-build.yaml
Upload MEDIUM trivy findings to GH security
> fix(actions): upload medium finding via trivy

- .github/workflows/ci-pr-title.yaml
This is for PRs that focus on the tests
> feat(ci): add tests as valid PR title scope

- charts/greenhouse/Chart.yaml
- charts/manager/alerts/operator.alerts
> fix(charts): invalid alert rule for PluginConstantlyFailing

- .github/ISSUE_TEMPLATE/epic.yaml
> feat(config): add epic template

- .github/ISSUE_TEMPLATE/epic.yaml
fixes linting issuse with the epic template
> fix(config): convert issue template to markdown

- charts/greenhouse/Chart.yaml
- charts/greenhouse/dashboards/controller-runtime.json
> fix(charts): use sd job for variable query

- .github/workflows/license.yaml
> fix(actions): rename secrets token to no collide with gh standard

- docs/user-guides/cluster/offboarding.md
- docs/user-guides/cluster/onboarding.md
Cluster off-boarding documentation
- Closes #646
- Closes #91
> docs(clusters): cluster off-boarding documentation

- charts/demo/templates/organization.yaml
- charts/greenhouse/Chart.yaml
The  field is called `mappedOrgAdminIdPGroup` instead of `mappedOrgAdminIDPGroup`
> fix(charts): typo in demo org resource

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-ingress-nginx.yaml
> fix(charts): enable cross-namespace lookup for ingress-controller

- pkg/controllers/plugin/pluginpreset_controller_test.go
- pkg/helm/diff_test.go
- pkg/test/fixtures/chartWithConfigMap/Chart.yaml
- pkg/test/fixtures/chartWithConfigMap/templates/configmap.yaml
- pkg/test/fixtures/chartWithConfigMap/values.yaml
Fix of the flaky test.
Normal automatic tests are covered the problem.
> fix(pluginpresets): fix flaky tests

- cmd/greenhouse/controllers.go
kubeconfig controller creates and manages `ClusterKubeconfig` resources to access on-boarded clusters. The controller was enabled by https://github.com/cloudoperators/greenhouse/pull/526/ but it looks like it is removed by https://github.com/cloudoperators/greenhouse/commit/bfaf3f3ad4a1a66ceb94970924459c82c9314cde
> fix(controller): add kubeconfig controller back

- charts/manager/crds/greenhouse.sap_plugins.yaml
- docs/reference/api/index.html
- docs/reference/api/openapi.yaml
- e2e/plugin/e2e_test.go
- pkg/apis/greenhouse/v1alpha1/plugin_types.go
- pkg/controllers/plugin/plugin_controller.go
Add diff field to Helm Release Status.
I updated the current E2E test.
> feat(plugins): add helm diff to status

- charts/demo/Chart.yaml
- charts/demo/templates/alertmanager-pluginconfig.yaml
- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-alerts.yaml
adds global values to alerts plugin
> chore(charts): add global values to alerts plugin

- .github/.goreleaser.yaml
- .github/CODEOWNERS
> fix(ci): no windows binaries in release

- pkg/rbac/role.go
All members of the organization should be able to query kubeconfig custom resource 
> feat(core): add clusterkubeconfigs to OrganizationMemberPolicyRules

- charts/idproxy/templates/rbac.yaml
> fix(idproxy): add rbac to idproxy as well for configmaps

- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/idproxy/Chart.yaml
- charts/idproxy/templates/_helpers.tpl
- charts/idproxy/templates/deployment.yaml
- charts/manager/Chart.yaml
- charts/manager/templates/_helpers.tpl
> fix(charts): typo in feature-flag template name, idproxy rm double env, chart bump

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-kube-monitoring.yaml
- charts/greenhouse/templates/plugin-thanos.yaml
Adding the thanos plugin to use the metrics long term storage capabilities of Greenhouse. 
> chore(charts): add thanos plugin

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-thanos.yaml
fixes a duplicated optionValues field on the thanos plugin
> fix(charts): remove duplicate optionValue from thanos plugin

- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/greenhouse/templates/plugin-ingress-nginx.yaml
This adds the option on the `ingress-nginx` Plugin to set annotations on the loadbalancer service. This allows to pass disco annotations, which can be used to create the A-Record for the `ingress-nginx` automatically. 
> feat(charts): template ingress-nginx annotations option

- pkg/controllers/organization/organization_controller_test.go
This adds an additional test to validate that the additional URIs on the `greenhouse` oauth2client are not overwritten when adding more URIs for additional orgs.
> feat(dex): additional test to validate URIs set on the default are kept

- website/package-lock.json
- fix npm vulnerability
- Related Issue - [Dependabot Security  Issue 47](https://github.com/cloudoperators/greenhouse/security/dependabot/47)
> chore(deps): fix npm vulnerability

- .github/CODEOWNERS
- .github/workflows/build-greenhousectl.yaml
rm /dev-env from `CODEOWNERS`
add /config to `CODEOWNERS`
ci disable standalone greenhousectl gh action 
> fix(ci): small fixes in CODEOWNERS and gh-actions

- charts/greenhouse/Chart.yaml
- charts/greenhouse/values.yaml
- Adds `kubectl oidc-login` URLs for dex
> chore(greenhouse): adds kubectl oidc-login URLs

- pkg/admission/plugin_webhook.go
The Heureka PluginDefinition can be installed in the Greenhouse cluster.
> feat(charts): enable heureka plugin in central cluster

- .github/workflows/ci-cleanup.yaml
- Makefile
- dev-env/README.md
- dev-env/docs.go
- pkg/internal/local/commands/dashboard.go
- pkg/internal/local/commands/setup.go
path for localenv was adjusted
remove dev-env image build from makefile
remove dev-env from ci-cleanup action
> docs(core): remove more mentions of dev-env

- charts/manager/crds/greenhouse.sap_pluginpresets.yaml
- charts/manager/crds/greenhouse.sap_plugins.yaml
- docs/reference/api/index.html
- docs/reference/api/openapi.yaml
- pkg/apis/greenhouse/v1alpha1/plugin_types.go
- pkg/controllers/plugin/helm_chart_testing.go
This field was added to the Plugin spec but never used.
> refactor(plugins): remove unused field .spec.disabled

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-thanos.yaml
This enables the ingress for thanos.
> feat(charts): enable ingress for thanos

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-thanos.yaml
> feat(charts): revert enable ingress for thanos

- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/greenhouse/templates/plugin-logs.yaml
- charts/greenhouse/templates/plugin-logshipping.yaml
- charts/greenhouse/values.yaml
This PR adds the logs plugin to the greenhouse clusters. 
> feat(charts): enable logs plugin

- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/greenhouse/templates/plugin-cert-manager.yaml
- charts/greenhouse/values.yaml
adds configurable webhook `timeoutSeconds` to cert-manager plugin
> fix(charts): adds webhook timeout to cert-manager plugin

- README.md
This updates the project description making it a bit more tangible and referencing our other projects integrated into the platform.
> docs(core): update readme

- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/greenhouse/values.yaml
increases cert-manager webhook timeout to 15s as default value
> chore(greenhouse): increases cert-manager webhook timeout

- .github/workflows/codeql.yaml
CodeQL only checks go code. Therefore we do not need to run it for non-code changes.
> fix(actions): only run codeql on go code changes

- cmd/greenhouse/main.go
- pkg/clientutil/log.go
- pkg/cmd/plugin_generate.go
- pkg/cmd/plugin_validate.go
- pkg/controllers/plugin/suite_test.go
- pkg/controllers/plugin/util.go
- pkg/controllers/plugin/util_test.go
- pkg/helm/helm.go
- pkg/helm/helm_test.go
- pkg/internal/local/helm/helm.go
- pkg/internal/local/setup/dashboard.go
- pkg/internal/local/setup/manifest.go
- pkg/internal/local/setup/webhook.go
- pkg/internal/local/utils/utils.go
- pkg/mocks/mock_Client.go
- pkg/mocks/mock_SubResourceWriter.go
`interface{}` and `any` can be used interchangeably, let's keep it consistent across the code base. 
> refactor(core): use any instead of interface{}

- cmd/greenhouse/main.go
- cmd/service-proxy/main.go
- pkg/controllers/organization/dex.go
- pkg/controllers/organization/organization_controller.go
- pkg/controllers/organization/service_proxy.go
- pkg/controllers/organization/teamrole_seeder.go
- pkg/dex/connector.go
- pkg/dex/connector_test.go
- pkg/helm/helm_test.go
- pkg/helm/suite_test.go
- pkg/test/env.go
Unifies the import alias for `greenhousev1alpha1`.
> refactor(core): update import alias for greenhousev1alpha1

- README.md
- docs/README.md
- docs/reference/api/openapi.yaml
- hack/install
- hack/openapi-generator/openapi-info.yaml
> fix(docs): remove mentioning of plusone

- .github/CODEOWNERS
> fix(core): add missing codeowners entry

- internal/controller/plugin/pluginpreset_controller.go
The used eventType was not valid.
> fix(pluginpresets): use corev1.EventTypeNormal

- internal/webhook/plugin_webhook.go
- internal/webhook/plugin_webhook_test.go
A Plugin deployed in the central cluster must be bound to the Organization. By setting a different .spec.releaseNamespace it was possible to deploy to a different organization.
This fix ensures that the Plugin namespace and .spec.releaseNamespace match
> fix(plugins): forbid deploying central plugins in other namespace

- api/well_known.go
- internal/controller/organization/organization_controller.go
- internal/controller/organization/service_proxy.go
- internal/controller/organization/service_proxy_test.go
add secret type for org secrets
filter reconciliation triggers for org based on secret type create technical org secret used by service_proxy to store generated values
> feat(organizations): create technical secret for generated values

- .github/renovate.json
- .github/workflows/codeql.yaml
- Dockerfile
- go.mod
> feat(core): bump go version to 1.24

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-ingress-nginx.yaml
> fix(charts): add large-client-header-buffer to ingress plugin

- internal/rbac/role.go
org admins should be able to view the logs of pods running in their org namespace
> feat(organizations): add pod logs to org admin rbac

- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/manager/Chart.yaml
- charts/manager/ci/test-values.yaml
- charts/manager/templates/manager/deployment.yaml
The indentation for the manager chart changed with #855, and needed adjustment on the templates.
Environment values for the manager to access postgres are readded
> fix(charts): fix indendation, add missing pg config

- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/manager/Chart.yaml
- charts/manager/templates/manager/deployment.yaml
- charts/manager/templates/webhook/deployment.yaml
- charts/manager/templates/webhook/service.yaml
- charts/manager/values.yaml
> fix(charts): readd manager replicas, fix webhook replicas

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/organization.yaml
> fix(charts): wrong secrets reference on org

- internal/controller/organization/service_proxy.go
the oauth2-proxy secret was moved to the internal secret
> fix(organizations): update secret reference to internal secret

- internal/controller/teammembership/teammembership_updater_controller_test.go
from time to time the condition was not set
test failed with a nil pointer
> fix(teams): remove flaky nil pointer

- internal/test/resources.go
`WithPluginOptionValue()` did not set the Value if the option did not previously exist in the Plugins spec
> fix(tests): set new pluginoption values on fixture

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-thanos.yaml
- charts/greenhouse/values.yaml
- makes thanos plugin optional
- uses `.Values.global.dnsDomain for the thanos ingress host
> fix(charts): make thanos plugin optional

- charts/greenhouse/Chart.yaml
- charts/greenhouse/templates/plugin-thanos.yaml
> fix(charts): broken thanos template

- .github/licenserc.yaml
- charts/manager/crds/greenhouse.sap_clusterkubeconfigs.yaml
- charts/manager/crds/greenhouse.sap_clusters.yaml
- charts/manager/crds/greenhouse.sap_organizations.yaml
- charts/manager/crds/greenhouse.sap_plugindefinitions.yaml
- charts/manager/crds/greenhouse.sap_pluginpresets.yaml
- charts/manager/crds/greenhouse.sap_plugins.yaml
- charts/manager/crds/greenhouse.sap_teammemberships.yaml
- charts/manager/crds/greenhouse.sap_teamrolebindings.yaml
- charts/manager/crds/greenhouse.sap_teamroles.yaml
- charts/manager/crds/greenhouse.sap_teams.yaml
This change ensures the license year is automatically set to the current year for new files.
For the CRDs generated with controller-gen we are only able to set the generator options as such:
`$(CONTROLLER_GEN) crd:year=2024,headerFile="./hack/license-header.yaml" paths="./api/..." output:crd:artifacts:config=hack/crd/bases`
with a YAML as such 
```yaml
```
On each generation the year will be updated, so I omitted this from the PR.
> fix(actions): set current year in spdx for new files

- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/manager/Chart.yaml
- charts/manager/alerts/operator.alerts
This alert is to make it visible if the members of a team drop.
> feat(teams): alert for drop in members count

- charts/cors-proxy/Chart.yaml
- charts/cors-proxy/templates/_helpers.tpl
- charts/cors-proxy/templates/deployment.yaml
- charts/cors-proxy/values.yaml
- charts/dashboard/Chart.yaml
- charts/dashboard/ci/test-values.yaml
- charts/dashboard/templates/_helpers.tpl
- charts/dashboard/templates/deployment.yaml
- charts/dashboard/values.yaml
- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/greenhouse/ci/test-values.yaml
- charts/idproxy/Chart.yaml
- charts/idproxy/templates/_helpers.tpl
- charts/idproxy/templates/deployment.yaml
- charts/idproxy/values.yaml
- charts/manager/templates/_helpers.tpl
- charts/manager/templates/manager/deployment.yaml
- charts/manager/templates/webhook/deployment.yaml
- charts/manager/values.yaml
This is to enable deploying from the current image tagged as main.
> feat(charts): add setting of image digest

- internal/controller/organization/organization_controller_test.go
- internal/controller/organization/service_proxy_test.go
- internal/controller/organization/teamrole_seeder_test.go
- internal/controller/plugin/pluginpreset_controller_test.go
- internal/controller/plugin/remote_cluster_test.go
- internal/controller/plugin/suite_test.go
- internal/controller/teammembership/teammembership_updater_controller_test.go
- internal/test/resources.go
- internal/test/setup.go
> refactor(tests): use resource helpers

- api/v1alpha1/plugin_types.go
- charts/manager/crds/greenhouse.sap_pluginpresets.yaml
- charts/manager/crds/greenhouse.sap_plugins.yaml
- docs/reference/api/index.html
- docs/reference/api/openapi.yaml
- docs/user-guides/plugin/plugin-deployment.md
- internal/controller/organization/service_proxy.go
- internal/controller/plugin/pluginpreset_controller.go
- internal/controller/plugin/pluginpreset_controller_test.go
- internal/controller/plugin/remote_cluster_test.go
- internal/controller/plugin/suite_test.go
- internal/helm/helm.go
- internal/test/resources.go
- internal/webhook/plugin_webhook.go
- internal/webhook/plugin_webhook_test.go
- internal/webhook/pluginpreset_webhook.go
Helm limits the length of the release name to 53 chars Currently the Plugin name is used as the releaseName. With PluginPresets this name consists of PluginPreset name
+ Cluster name, which can get longer.
This PR changes the behavior for new Plugins to have either the releaseName from the PluginSpec or use the PluginDefinitions HelmChart name.
The name is limited to 53 characters in both cases.
- for existing Plugins the Name of the plugin will be used
- for newly created Plugins the ReleaseName is used if set, else the name of the HelmChart is used
- releaseName is optional until set
> feat(plugins): add ReleaseName field and defaulting logic

- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/manager/Chart.yaml
- charts/manager/templates/cert/issuer.yaml
fixes Issuing certificate namespace (defaults to namespace the chart is deployed to)
> fix(charts): removes namespace from issuer certificate

- docs/architecture/high-level.md
This updates the high-level architecture section of the documentation.
> docs(greenhouse): updates architecture documentation

- .github/workflows/ci-e2e-test.yaml
> fix(ci): fix e2e workflow branch revision

- internal/clientutil/predicates.go
There is no usage for these predicates
> refactor(utils): remove unused predicates

- website/assets/scss/_custom_styles_project.scss
- website/hugo.yaml
- website/layouts/_default/baseof.html
- website/layouts/partials/footer-custom-area.html
- website/layouts/partials/footer.html
- website/layouts/partials/landing-page-footer-custom-area.html
> feat(docs): add lfe footer to website

- .github/workflows/helm-lint.yaml
- .github/workflows/helm-push.yaml
- RELEASE.md
release automation is only triggered when a tag is pushed the helm chart should not be versioned/uploaded besides when greenhouse is released
> refactor(ci): upload helm charts only on tagged commits

- website/layouts/partials/footer-custom-area.html
- website/layouts/partials/landing-page-footer-custom-area.html
> refactor(docs): update copyright footer

- internal/webhook/v1alpha1/plugin_webhook.go
* add kube-monitoring and thanos
* add perses
> feat(webhook): allow kube-monitoring and thanos (#1238)

- internal/webhook/v1alpha1/plugin_webhook.go
- internal/webhook/v1alpha1/plugin_webhook_test.go
Previously a generic not found error was raised if the PluginDefinition was not specified.
This makes the error more explicit, where a required field missing error is returned if the `.spec.PluginDefinition` is not supplied. Not found and any other api errors are put into respective field errors as well.
> feat(plugins): improved error for invalid plugindefinition

- .github/workflows/check-changes-crd-api.yaml
- .github/workflows/license.yaml
> feat(ci): use app token, specify permissions

- internal/controller/cluster/metrics.go
Quick fix missing metric register
> fix(clusters): registers cluster_ready metric

- internal/controller/catalog/catalog_controller.go
- internal/controller/catalog/catalog_controller_test.go
- internal/controller/organization/organization_controller.go
- internal/controller/organization/organization_controller_test.go
- internal/controller/organization/rbac.go
- internal/flux/kustomize_builder.go
- internal/rbac/role.go
- internal/rbac/util.go
- Closes https://github.com/cloudoperators/greenhouse/issues/1321
> feat(catalogs): provision ServiceAccount for Catalog

- charts/greenhouse/Chart.yaml
> chore(charts): bump version to 0.12.0

- .github/workflows/backport.yaml
> fix(ci): adjust regex for backport label

- charts/cors-proxy/Chart.yaml
- charts/cors-proxy/values.yaml
- charts/greenhouse/Chart.lock
- charts/greenhouse/Chart.yaml
- charts/idproxy/Chart.yaml
- charts/idproxy/values.yaml
- charts/manager/Chart.yaml
- charts/manager/values.yaml
> release(charts): bump versions

- charts/greenhouse/Chart.yaml
> fix(charts): bump greenhouse chart

- .github/workflows/deploy-github-pages.yaml
Quick fix for deploying Hugo docs. Search for ClusterPluginDefinition kind instead of PluginDefinition in greenhouse-extensions repo.
> fix(actions): look for ClusterPluginDefinition kind for Hugo docs

- cmd/greenhouse/main.go
Create custom leader election options such as leaseDuration, renewDeadline and retryPeriod
> feat(greenhouse): pass leader election opts via flags from container args
